### PR TITLE
test for SHA || MD5 passwords before testing problematic crypt().

### PR DESCRIPTION
**Pull request by davehorner**
strawberry perl crypt was crashing during t/password.t
for more background check: https://rt.cpan.org/Ticket/Display.html?id=100750

### CODE REVIEW

**Comment by chansen** [comment]
Unfortunately I have been lacking in support for Auten::Simple related modules, would you be interested in becoming a co-maintainer?

**Comment by davehorner** [comment]
I would be willing to help  -- sure I can help co-maintain.  

I hope my patch would resolve the other strawberry perl issue (https://rt.cpan.org/Ticket/Display.html?id=92158), which is reporting the binary md5/sha errors but provides no solution.  It is sad that strawberry Config is reporting it has crypt but crashes.. same with fork() I've found...the moving crypt() lower might resolve it.

https://rt.cpan.org/Ticket/Display.html?id=26465 <-- will require some additional testing and time to understand...

Thanks Christian.

**Comment by chansen** [comment]
I have given you collaborator status for:
chansen/p5-authen-simple
chansen/p5-authen-simple-ldap

And I have added you as a co-maintainer for following CPAN modules at PAUSE:
Added MRHORNER to co-maintainers of Authen::Simple.
Added MRHORNER to co-maintainers of Authen::Simple::ActiveDirectory.
Added MRHORNER to co-maintainers of Authen::Simple::Adapter.
Added MRHORNER to co-maintainers of Authen::Simple::Apache.
Added MRHORNER to co-maintainers of Authen::Simple::CDBI.
Added MRHORNER to co-maintainers of Authen::Simple::DBI.
Added MRHORNER to co-maintainers of Authen::Simple::DBM.
Added MRHORNER to co-maintainers of Authen::Simple::FTP.
Added MRHORNER to co-maintainers of Authen::Simple::HTTP.
Added MRHORNER to co-maintainers of Authen::Simple::Kerberos.
Added MRHORNER to co-maintainers of Authen::Simple::LDAP.
Added MRHORNER to co-maintainers of Authen::Simple::Log.
Added MRHORNER to co-maintainers of Authen::Simple::NIS.
Added MRHORNER to co-maintainers of Authen::Simple::PAM.
Added MRHORNER to co-maintainers of Authen::Simple::POP3.
Added MRHORNER to co-maintainers of Authen::Simple::Passwd.
Added MRHORNER to co-maintainers of Authen::Simple::Password.
Added MRHORNER to co-maintainers of Authen::Simple::RADIUS.
Added MRHORNER to co-maintainers of Authen::Simple::SMB.
Added MRHORNER to co-maintainers of Authen::Simple::SMTP.
Added MRHORNER to co-maintainers of Authen::Simple::SSH.

All I ask is that you don't deliberately break the API. Authen::Simple and it's adapters is used by many authors and institutions/corporations. If you have any questions or need guidance don't hesitate to ask me for it. I'm really looking forward to working with you, and this will probably be a nice experience for you as a CPAN author/maintainer.

I'm available on chansen@cpan.org or chansen at irc.perl.org.

I'm really grateful for your interest in maintaining and developing Authen::Simple and it's adapters in a future direction =)

**Comment by chansen** [comment]
@davehorner,
Perhaps the above comment was to bold of me and intimidating. Please let me know how you would like to contribute.

**Comment by davehorner** [comment]
Sorry Christian, you are correct that it was a little overwhelming seeing
21 modules.  It's quite alright though.  I'm interested in getting up to
speed on all the modules which is going to require some time to test and
try the modules.
I'd like to start with the patch I submitted and testing to see if that
resolves the issues I was experiencing p5-authen-simple.
This is a first for me being collaborator and co-maintainer, I very much
appreciate the opportunity. Thank you.
Is there anything special I need to do aside from "Merge pull request"
within github to get my patch within CPAN?

Cheers,
--dave

**Pull request merged**
